apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tbupvm56i-go 
  janus-idp.io/tekton: tbupvm56i-go
  backstage.io/kubernetes-id: tbupvm56i-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tbupvm56i-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  